### ISSUE TITLE
Explicitly prevent network access?

### ISSUE THREAD

**Issue by davidkassa** [Yac-Team/ohtipi#1]
I love this idea. The permissions and the fact that you're on my local machine with a fresh OTP makes me (obviously) nervous. Is there a way to explicitly prohibit an app from having network access? If so, can you include this in your instructions?

**Comment by itsthisjustin** [comment]
If we completely prohibit network we couldn't do app updates. We were CONSIDERING having a server side "whitelist" of 2fa formats that the app can detect as well. It wouldn't _actually_ present any security concern but it might make it look like one. Thoughts?

**Comment by davidkassa** [comment]
These are great considerations. And a tough beast to tame. Local system
access (potentially to a password manager) and fresh OTP makes this a scary
app. I'm not sure if there's a reasonable way around that - especially with
server-side features.

In theory, any local app can do the same thing so maybe it just comes down
to a trust issue. Open Source helps with that along with your candor.

**Comment by alectrocute** [comment]
@davidkassa Try downloading [Little Snitch](https://www.obdev.at/products/littlesnitch/index.html) and observing/blocking Ohtipi's traffic as desired. You'll see that it only phones home to check for new releases (blocking this will prevent Ohtipi from autoupdating).
