### ISSUE TITLE
Disable or change resync and copy shortcut?

### ISSUE THREAD

**Issue by BrettBedarf** [Yac-Team/ohtipi#11]
Is there a way to disable or change the resync and copy shortcut without editing config.js and building myself?

I was going nuts trying to figure out why the VSCode open explorer shortcut no longer works until I discovered Cmd+Shift+E sending to Ohtipi...

thanks!

**Comment by itsthisjustin** [comment]
Yeah we can add a way to edit the shortcut. I'll see if I can add that to the upcoming release

**Comment by rahul286** [comment]
Yep. For me, CMD + SHIFT + E is used mostly to "center align" text in Google Docs.

So an option to disable the shortcut or change it to something else will be of great help.

**Comment by alectrocute** [comment]
This will be resolved with a new feature in the upcoming release this week, thanks @rahul286 and @BrettBedarf!
