### ISSUE TITLE
Helper keeps persisting

### ISSUE THREAD

**Issue by SkarDude** [Yac-Team/ohtipi#12]
![image](https://user-images.githubusercontent.com/12519126/150405249-aab36137-bc9c-4302-8063-c341ed94ccde.png)

Trying to figure out how to get this tried updating, restarting, and uninstalling.

**Comment by alectrocute** [comment]
Hey, any chance Ohtipi isn't in your `~/Applications` folder?

**Comment by SkarDude** [comment]
> Hey, any chance Ohtipi isn't in your `~/Applications` folder?

It is in `~/Applications`

**Comment by alectrocute** [comment]
Try running `sudo chown -R $USER:wheel /Applications/Ohtipi.app` in Terminal.app to reset Ohtipi's permissions, this is typical behavior for an app that can't write data due to bad permissions. Let me know if that works!

**Comment by alectrocute** [comment]
If this doesn't work, can you ensure you're a system admin on the macOS machine you're using Ohtipi on?

**Comment by SkarDude** [comment]
> Try running `sudo chown -R $USER:wheel /Applications/Ohtipi.app` in Terminal.app to reset Ohtipi's permissions, this is typical behavior for an app that can't write data due to bad permissions. Let me know if that works!

`sudo chown -R $USER /Applications/Ohtipi.app`

This ended up working had to strip the `:wheel`
