### ISSUE TITLE
Does not work with Bank of America message

### ISSUE THREAD

**Issue by sinak** [Yac-Team/ohtipi#14]
BoA is one of the biggest banks in the US. Their 2FA SMS codes look like this:

> <#>BofA: DO NOT share this Sign In code. We will NEVER call you or text you for it. Code 123456. Reply HELP if you didn't request it. 

Ohtipi doesn't seem to find them for some reason. Would love if it did, as you need to do 2FA ridiculously often.

**Comment by itsthisjustin** [comment]
Added to our internal task tracker

**Comment by alectrocute** [comment]
@sinak Fixed, will be released this week!
