### ISSUE TITLE
Full Disk Access Permission Loop

### ISSUE THREAD

**Issue by bslatyer** [Yac-Team/ohtipi#15]
Hi @Yac-Team,

I believe there is an issue with **Ohtipi** and **"Full Disk Access".** 

I've downloaded the app, allowed it **"Full Disk Access"** in System Preferences and then relaunched the application. Ohtipi will start up again and request the same **"Full Disk Access"** permission as if it is stuck in a **"Request for Full Disk Access"** loop. This happens on both the **Gumroad** & **Setapp** versions of the app on the **macOS Monterey Beta (12.3).** However, this doesn't seem to effect the current public release of **macOS Monterey (12.2).**

**System Information**
**macOS Version:** macOS Monterey 12.3 Developer Beta 2 (21E5206e)
**Ohtipi Version:** 1.0.20 (Non Setapp) & 1.0.19 (Setapp)
**Mac Model:** MacBookAir10,1

**Permission Granted for Full Disk Access**
<img width="780" alt="Screen Shot 2022-02-10 at 16 58 01" src="https://user-images.githubusercontent.com/64551242/153347199-000ec2fb-fd73-45c1-83ec-efd16576d11f.png">

**Application Shows as Permission Granted**
<img width="912" alt="Screen Shot 2022-02-10 at 16 59 05" src="https://user-images.githubusercontent.com/64551242/153347260-62b606d9-f2ec-40d0-9c71-80cb276321e2.png">

**Comment by alectrocute** [comment]
I've looked into it and it appears it's an issue with [node-mac-permissions](https://github.com/codebytere/node-mac-permissions) on beta macOS. I'll file a ticket over there for hope of a resolve, thanks @bslatyer!

**Comment by bslatyer** [comment]
> I've looked into it and it appears it's an issue with [node-mac-permissions](https://github.com/codebytere/node-mac-permissions) on beta macOS. I'll file a ticket over there for hope of a resolve, thanks @bslatyer!

No worries, happy to help.

**Comment by bslatyer** [comment]
Hey @alectrocute 

Do you have an update on this issue yet?

**Comment by bslatyer** [comment]
Hey @alectrocute

Is there an update on this issue yet?

**Comment by tony2019666** [comment]
Hi https://github.com/Yac-Team,
l'm a Setapp subscriber and I'm using Ohtipi, Ohtipi used to works well on macOS 12.2 but when I update macOS to 12.3 the Ohtipi has the same problem of loop ask for full disk access

my device :MacBook Pro (16-inch, 2019)
ver of Ohtipi: 1.0.19 (1.0.19)

macOS 12.3 is now an official stable release for users so I hope Ohtipi can solve the problem soon

**Comment by itsthisjustin** [comment]
Hey Tony, will look into this asap.

**Comment by bslatyer** [comment]
Hey,

Is there any update on this bug?

It's unusable on macOS Monterey 12.3 with the Setapp version.

**Comment by bslatyer** [comment]
Hey @itsthisjustin & @alectrocute 

Are there any updates coming for users facing this issue on macOS 12.3 and later? 

The app is currently unusable and we're not getting any communication on what's getting done about this.

**Comment by itsthisjustin** [comment]
Apologies @bslatyer there's not a ton of internal priority for this. It IS open source so anyone can lend a hand in fixing this. I checked the package we are using and it doesn't seem to have been updated to fix this issue yet. I may just re-write this entire thing natively though so standby for that.

**Comment by deepesh-agarwal** [comment]
@itsthisjustin I paid money to support you and get support but it seems that is absent, pls. share where and how to add OTP templates in the code so I can help myself and get this working.

**Comment by tony2019666** [comment]
I'm also a paid user, as a setapp subscriber. So in a way I'm paid to subscribe your app. I hope there will be an update soon otherwise we(as the subscriber instead of open source contributors)also can ask setapp to remove this app and change to something new.

**Comment by itsthisjustin** [comment]
Working on an update that should be available in a week or so. Will also enable the community to add to the code whitelist

**Comment by bslatyer** [comment]
Thank you for the communication on this issue @itsthisjustin. I'll try to lend a hand in fixing this issue should you need it.

**Comment by bslatyer** [comment]
Hey @itsthisjustin @alectrocute 

Is there any news on a new update fixing this issue yet?

**Comment by itsthisjustin** [comment]
App will be released in the next day or so. I'll update everyone when it's ready.

**Comment by bslatyer** [comment]
@itsthisjustin No worries, thanks for the update.

**Comment by deepesh-agarwal** [comment]
@itsthisjustin Eagerly waiting for the update.

**Comment by bslatyer** [comment]
Hey @itsthisjustin @alectrocute 

Any news on the new update yet?

**Comment by itsthisjustin** [comment]
I've just remade the whole app in native Swift. I no longer have the permission loop issue on the latest macOS. You can grab it at https://2fhey.com and use code ohtipi for $5 off
