### ISSUE TITLE
SetApp update

### ISSUE THREAD

**Issue by sinak** [Yac-Team/ohtipi#18]
It looks like the version on SetApp was last updated on 9/30/21 (1.0.19) but there have been a whole lot of improvements since then. Any chance the SetApp version can be more regularly updated?

**Comment by itsthisjustin** [comment]
Working on that tonight!

**Comment by sinak** [comment]
Any update @itsthisjustin? Thanks!

**Comment by alectrocute** [comment]
It has been updated on Setapp @sinak!

**Comment by sinak** [comment]
Thank you!
