### ISSUE TITLE
Ohtipi not showing paste window on Brave browser

### ISSUE THREAD

**Issue by donutshredda** [Yac-Team/ohtipi#19]
Confirmed working in Safari but not on Brave. M1 Macbook Pro (2020), MacOS 12.3, Brave version V1.36.122, Chromium 99.0.4844.88

**Comment by itsthisjustin** [comment]
The browser won't make any difference as we just paste the code to a tooltip. What you're seeing in Safari might be just the native feature from Apple. Are you sure it's not just one specific provider that isn't being recognized by Ohtipi?

**Comment by donutshredda** [comment]
You are correct, my most common website that uses 2fa doesn't seem to be picked up by the app. Tried another website not commonly used and works as intended. For example the troubled website sends the SMS as follows -
_Websitename_ verification code: xxxxxx

**Comment by itsthisjustin** [comment]
If you add the exact copy it uses we can whitelist it in the next release

**Comment by donutshredda** [comment]
Sure, here is the SMS -
Mimecast verification code: xxxxxx
