### ISSUE TITLE
Why does ohtipi require full disk access?

### ISSUE THREAD

**Issue by Shubhang** [Yac-Team/ohtipi#2]
The app's description as to why this permission is needed is vague. Would love to know why this permission is needed!

**Comment by itsthisjustin** [comment]
> The app's description as to why this permission is needed is vague. Would love to know why this permission is needed!

Only way for the app to read the iMessage database on macOS unfortunately. Bluebubbles and Airmessage require the same permission as well.

**Comment by alectrocute** [comment]
Let us know if you need further help, @Shubhang. Closing this ticket for now.
