### ISSUE TITLE
Pasting shows for irs.gov website does not seem to work

### ISSUE THREAD

**Issue by johndoux** [Yac-Team/ohtipi#20]
When pasting into irs.gov for multi factor auth, it doesn't seem to work and sometimes will only paste "https: " or it will past whatever I had last on my clipboard.  I tried cmd+shift+e but it will not paste the updated text message code.

**Comment by itsthisjustin** [comment]
Can you add the copy of the message they send you so that we can add it to the manual whitelist?

**Comment by johndoux** [comment]
IRS Gove Website:
- IRS Password Service: Your security code is 123456. Only enter this code on IRS.gov. Don't share this code with anyone. - Reply HELP for more information.

Also tried it here and doesn't work.
EVGA Website:
- EVGA verification code: TRM-123456,This code will expire in 15 minutes


So far other websites I've accessed currently work and it's great!

**Comment by itsthisjustin** [comment]
Alright, I've just remade the whole app in native code along with a remote file for adding supported codes that anyone can do a PR for. You can grab it at https://2fhey.com and use code ohtipi for $5 off

**Comment by johndoux** [comment]
Thanks! I’ll take a look at 2fhey

**Comment by deepesh-agarwal** [comment]
@itsthisjustin Where to enter code?

**Comment by itsthisjustin** [comment]
> @itsthisjustin Where to enter code?

Gumroad doesn't offer the code option til the next screen after you set a price and say you're gonna pay. Yeah I think it's kinda bad UX myself.

**Comment by johndoux** [comment]
Just got a chance to to download 2fhey with the code, thanks so much!!! It seems to have worked with the IRS website.  The EVGA website doesn't seem to be getting recognized, since the website only needs the digits and doesn't need the strings.  For example TRM-123456,  it requires only the "123456" portion to be entered and on the website ti'll show TRM-______

I'll take a look at the remote file and see if can do a PR.
