### ISSUE TITLE
Stuck at Verifying ".com.ohtipi.app.hoWEia"... on every boot

### ISSUE THREAD

**Issue by deepesh-agarwal** [Yac-Team/ohtipi#21]
I get this irritating window on every boot now, clicking the close/cancel icon does nothing.
<img width="454" alt="Screenshot 2022-05-05 at 3 43 54 PM" src="https://user-images.githubusercontent.com/3198004/166904349-39d20c2f-3974-4e29-82d5-e6d937b69eb9.png">

**Comment by itsthisjustin** [comment]
Hmm that's interesting. Are you a SetApp user?

**Comment by deepesh-agarwal** [comment]
No, gumroad purchase. What about the new version you were talking about?

**Comment by itsthisjustin** [comment]
Hoping to have it done today

**Comment by itsthisjustin** [comment]
This should no longer be an issue on the latest version at 2FHey.com. Use code ohtipi for the full $5 off
