### ISSUE TITLE
iMessage listening issue on macOS Mojave

### ISSUE THREAD

**Issue by Kas-tle** [Yac-Team/ohtipi#5]
Is this supposed to be compatable with macOS Mojave? I am currently running 10.14.6 and while the application claims it successfully syncs with iMessage, nothing appears to be copied to the clipboard.

**Comment by itsthisjustin** [comment]
Have not tested personally on Mohave so I'll try to get a hold of a machine.

**Comment by alectrocute** [comment]
@Kas-tle macOS 10.14.6 *should* be supported. Would you mind being more specific as to the problems you're running into? Is it detecting OTP's but failing to actually copy it into your clipboard?

**Comment by Kas-tle** [comment]
It claims to have synced the OTP, but on pasting the clipboard simply contains whatever previous string I had on it (never an OTP). The app does launch fine both manually and at login.

**Comment by Kas-tle** [comment]
I also should note I attempted to run manually with npm so I could see if that would give me any debugging output, but it failed on account of missing the header Sound.h, so I could not test it. I suspect it this is included in a more recent version of XCode command line tools than Mojave supports.

**Comment by alectrocute** [comment]
@Kas-tle Thanks. Does the tray icon menu reflect any actual OTP's, for example: `123456 (Google)`?

**Comment by Kas-tle** [comment]
I attempted a few times and the notification icon via iMessage came through, but at no point did the tray menu actually refer to an OTP.

**Comment by alectrocute** [comment]
@Kas-tle Is there any possible way to get Ohtipi up and running in development (clone this repo, etc. like you previously mentioned trying)? Try downloading [`nvm`](https://github.com/nvm-sh/nvm#install--update-script) and toggling between node versions 12 and 14 to see if that helps the install process.

Any error messages, etc. are critical to get here to fix the issue. Since Ohtipi doesn't send anything back to us, I don't have any remote error reporting to rely on (eg. Sentry).

EDIT – I've managed to spin up a Mojave VM on my Big Sur MacBook, but can't get iMessage activated. Can't really proceed further without getting a physical Mojave machine.

**Comment by Kas-tle** [comment]
Due to https://github.com/codebytere/node-mac-permissions/issues/12 I had to use a deprecated version of node-mac-permissions (2.1.2). I granted terminal full disk access. On running `npm run dev` and performing the same test with regards to an OTP, there is no output in the terminal. Resyncing also does not provide any terminal output. Is there any form of additional logging I could enable?

**Comment by alectrocute** [comment]
@Kas-tle Try setting `dev.debug` to `true` here: https://github.com/Yac-Team/ohtipi/blob/main/src/config.js

This should log OTP results in console so you can determine if the queries are successful.

**Comment by Kas-tle** [comment]
@alectrocute Interestingly it appears that it is picking up the OTPs. Here is an excerpt:
```js
{
  step: 0,
  service: undefined,
  string: "paypal: your security code is: XXXXXX. it expires in 10 minutes. don't share this code with anyone."
}
{
  step: 1,
  matchedOnLevel: 1,
  matchedObject: { code: 'XXXXXX', service: undefined, level: 1 }
}
{
  step: 2,
  secondPassResult: { code: 'XXXXXX', service: undefined },
  original: {
    obj: { code: 'XXXXXX', service: undefined },
    message: "PayPal: Your security code is: XXXXXX. It expires in 10 minutes. Don't share this code with anyone."
  }
}
```
Is it be possible that it is merely the clipboard function that is failing somehow?

**Comment by alectrocute** [comment]
Hey @Kas-tle, can you `git pull origin main` and try again? Made a tweak that should fix this.

**Comment by Kas-tle** [comment]
@alectrocute Yes that was indeed it. I am sorry that I did not initially realize that this only works with defined known services (assumed it was just some kind of generic regex looking for a 6 digit code). Perhaps it would be worth linking to https://github.com/Yac-Team/ohtipi/blob/main/src/libs/parse-otp-message/lib/known-services.js on the readme and specifying that these are supported services? Regardless, sorry for taking up your time with this. I should have dug deeper initially.

**Comment by alectrocute** [comment]
Agreed, @Kas-tle! It's linked on https://github.com/Yac-Team/ohtipi#find-the-important-bits but obviously not visible enough. I'll fix soon! :)
