### ISSUE TITLE
"Full Disk Access" is granted but doesn't persist during local development

### ISSUE THREAD

**Issue by adamfeldman** [Yac-Team/ohtipi#6]
I am struggling with running this locally. I will contribute regex for a couple USA businesses – Chase and T-Mobile.

I have the app running locally on macOS 11.5.2, via `npm run dev`. 

I gave Electron.app Full Disk Access by dragging it into System Preferences. However I can't get the app into a state where it can read the iMessage sqlite (per logs). When I restart the app using the in-app button, it always prompts me to enable Full Disk Access, despite it already being on.

I'm not deeply familiar with Electron and am unsure what to try next.

Thank you for building ohtipi! Discovered it in Setapp.

https://user-images.githubusercontent.com/133385/131880253-9f96c561-1cb1-403e-a156-05d442861114.mp4

**Comment by alectrocute** [comment]
Hey @adamfeldman, thanks for the wonderful ticket with all the info & video!

When in development, you'll have to grant Full Disk Access to whatever is launching Ohtipi (and in extension, the `Electron.app` binary), in this case either `Terminal.app` or `Visual Studio Code.app`. Let me know if this works for you.

If this works for you – I will be adding a note about this in our public-facing documentation.

**Comment by alectrocute** [comment]
PS - For the services that aren't being detected, try adding them to [this array](https://github.com/Yac-Team/ohtipi/blob/main/src/assets/libs/parse-otp-message/lib/known-services.js) and seeing if that does the trick.

**Comment by adamfeldman** [comment]
> When in development, you'll have to grant Full Disk Access to whatever is launching Ohtipi (and in extension, the `Electron.app` binary), in this case either `Terminal.app` or `Visual Studio Code.app`. Let me know if this works for you.

Thank you @alectrocute! As I'm running my terminal within VS Code, adding that fixed the issue with Full Disk Access.

For adding the services, I'm using the recent PR #4 as an example. Am running the `npm run test` to try and get a sense of if what I'm doing is working. So far no luck with getting the running dev app to pickup my OTP SMS :)

**Comment by adamfeldman** [comment]
Wasn't clear in my earlier comment – am going to continue working with this, another day soon.
