### ISSUE TITLE
M1 Support

### ISSUE THREAD

**Issue by vektren** [Yac-Team/ohtipi#9]
Hello, I went through the payment option and moved the app from the old computer to the new one. Is there a native M1 version released?

**Comment by itsthisjustin** [comment]
@alectrocute is the universal binary available outside of setapp?

**Comment by vektren** [comment]
I discovered it through SetApp but as I own most of the tools offered in SetApp I picked it up outside of SetApp. 

The download link won't work anymore assuming it expired? Would be great if there is a universal app available.

**Comment by itsthisjustin** [comment]
Gumroad should let you re-download. If universal binary isn't there then I'll add it

**Comment by vektren** [comment]
It opens and then closes the browser (Brave) window like it would start downloading but nothing downloads. 
I just copied the link to Safari, and that downloaded a new copy, however not universal. 

EDIT: Added Brave as primary browser.

**Comment by nicoelayda** [comment]
I just downloaded this through Gumroad too. The dmg file only contains an Intel-only binary.

**Comment by itsthisjustin** [comment]
Sounds like we just need to update the base file you download before you get the OTA update. I'll make a point to get this done this week.

**Comment by vektren** [comment]
Thanks, will try again early next week.

**Comment by itsthisjustin** [comment]
Hey @blueteq here's a direct link to the universal binary with m1 support. https://sofriendly.s3.amazonaws.com/Ohtipi.zip

**Comment by itsthisjustin** [comment]
> Hey @blueteq here's a direct link to the universal binary with m1 support. 

Actually it's uploaded to GumRoad now so you can just grab it from there. I'm gonna remove the link from github so people can't bypass gumroad for free.

**Comment by itsthisjustin** [comment]
Gumroad has been updated with separate intel and m1 builds. You can download from there and auto updates will grab the correct architecture moving forward!
